### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by tanjie860110** [kylc/fpga_stereo_vision#1]
when i do this 'make compile_stereobm_core_tb', the error happened :
clang src/*.c test/stereobm_core_tb.c -o stereobm_core_tb -std=c99 -Wall -Wno-unknown-pragmas -O2 -Iinclude/ -I/usr/include/netpbm -lnetpbm -lm
/bin/sh: 1: clang: not found
Makefile:6: recipe for target 'compile_stereobm_core_tb' failed
make: *** [compile_stereobm_core_tb] Error 127
Can you help me? Thank you. @kylc

**Comment by tanjie860110** [comment]
@kylc

**Comment by tanjie860110** [comment]
when i use command g++ instead clang, it makes some mistakes such as:

g++ -o stereobm_core_tb test/stereobm_core_tb.c `pkg-config --cflags` -std=c++11
Must specify package names on the command line
In file included from test/stereobm_core_tb.c:3:0:
test/tb_util.c:1:17: fatal error: pam.h: No such file or directory
compilation terminated.

I want to know why?Can this project run only on fpga and not run on x86?  Thank you very much. @kylc

**Comment by kylc** [comment]
You'll need to install the libnetpbm library, which includes pam.h.

**Comment by tanjie860110** [comment]
@kylc thank you.I have solved this problem.
